version: '3.2'
services:
  web:
    build: ./helloserver
    ports:
    - target: 5000
      published: 5000
    volumes:
    - type: bind
      source: ./helloserver
      target: /app
  redis:
    image: "redis:alpine"